'use strict';
(()=>{
const $=id=>document.getElementById(id),T=window.THREE,bags=window.BOUTIQUE_BAGS;
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});}catch(e){$('failure').hidden=false;return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('scene').appendChild(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#302820');scene.fog=new T.Fog('#302820',17,35);const camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.05,60);camera.position.set(0,2.25,10.8);
const gold=new T.MeshStandardMaterial({color:0xbfa06b,metalness:.75,roughness:.3}),walnut=new T.MeshStandardMaterial({color:0x36271e,roughness:.7}),cream=new T.MeshStandardMaterial({color:0xd8c8b0,roughness:.65}),black=new T.MeshStandardMaterial({color:0x25221f,roughness:.55});
function marble(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.fillStyle='#c6b79e';x.fillRect(0,0,512,512);for(let i=0;i<170;i++){x.strokeStyle=`rgba(103,84,62,${.015+(i%7)*.005})`;x.lineWidth=1+i%3;x.beginPath();for(let j=0;j<20;j++){const xx=j*28,yy=i*6+Math.sin(j*.4+i)*15;j?x.lineTo(xx,yy):x.moveTo(xx,yy);}x.stroke();}const texture=new T.CanvasTexture(c);texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.repeat.set(3,3);return new T.MeshStandardMaterial({map:texture,roughness:.42});}
const stone=marble();function box(w,h,d,x,y,z,m,parent=scene){const q=new T.Mesh(new T.BoxGeometry(w,h,d),m);q.position.set(x,y,z);q.castShadow=true;q.receiveShadow=true;parent.add(q);return q;}
function tube(points,r,m,parent){const curve=new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p)));const q=new T.Mesh(new T.TubeGeometry(curve,40,r,8,false),m);q.castShadow=true;parent.add(q);return q;}
box(16,.15,22,0,-.1,1,stone);box(16,5,.22,0,2.5,-8,cream);box(.25,5,22,-8,2.5,1,cream);box(.25,5,22,8,2.5,1,cream);box(16,.2,22,0,5,1,cream);
for(let x=-7;x<=7;x+=2){box(.035,.006,22,x,.001,1,gold);box(.065,4.7,.04,x,2.4,-7.85,gold);}for(let z=-7;z<=11;z+=2)box(16,.006,.025,0,.002,z,gold);
box(14,.22,.4,0,.25,-7.7,walnut);box(14,.2,.4,0,4.7,-7.7,walnut);
function label(text,w=3,h=.6,color='#d6be8f'){const c=document.createElement('canvas');c.width=1024;c.height=160;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.textAlign='center';ctx.font='48px Georgia';ctx.fillText(text,512,94);const q=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),transparent:true}));return q;}
let logo=label('F O R M E',4,.7);logo.position.set(0,3.75,-7.82);scene.add(logo);let sub=label('LA BOUTIQUE DES ICÔNES',3,.4);sub.position.set(0,3.2,-7.8);scene.add(sub);
scene.add(new T.HemisphereLight(0xffe8c5,0xb6a992,1.3));scene.add(new T.AmbientLight(0xffffff,.5));const key=new T.DirectionalLight(0xffeed9,1.05);key.position.set(2,8,7);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-10,right:10,top:10,bottom:-10});key.shadow.bias=-.001;scene.add(key);
function spotlight(x,z){const light=new T.SpotLight(0xffddac,1.5,12,.48,.7,1);light.position.set(x,4.65,z+1);light.target.position.set(x,1.3,z);scene.add(light,light.target);const disk=new T.Mesh(new T.CylinderGeometry(.16,.16,.04,24),gold);disk.position.copy(light.position);scene.add(disk);}
// Central inspection table; all coordinates are metres, bag dimensions come from the atlas.
box(2.65,.14,1.65,0,1.02,1.4,stone);box(1.6,.92,.8,0,.48,1.4,walnut);box(1.66,.06,.86,0,.07,1.4,gold);const tray=new T.Mesh(new T.CylinderGeometry(.53,.53,.045,64),black);tray.position.set(0,1.12,1.4);tray.receiveShadow=true;scene.add(tray);spotlight(0,1.4);
// Side seating and fluted wall details.
for(const s of [-1,1]){box(1.5,.3,3,s*6.7,.48,5,walnut);box(1.45,.24,2.9,s*6.7,.73,5,cream);for(let z=-7;z<11;z+=.3)box(.035,4,.05,s*7.82,2.2,z,walnut);}
const models=[],hitObjects=[],homes=[];const placements=[[-4.6,-4.8],[0,-5.5],[4.6,-4.8],[-5.5,.2],[5.5,.2],[3.2,-2.4]];
function buildProxy(b,i){const group=new T.Group(),w=b.dims[0]/30,h=b.dims[1]/30,d=b.dims[2]/30;const mat=new T.MeshStandardMaterial({color:[0x9b5232,0x375b4d,0x211e20,0x60412a,0x8c3047,0xc9ac78][i],roughness:.64});const shape=new T.Shape();b.outline.forEach(([x,y],k)=>k?shape.lineTo((x-.5)*w,(1-y)*h):shape.moveTo((x-.5)*w,(1-y)*h));shape.closePath();const geo=new T.ExtrudeGeometry(shape,{depth:d,bevelEnabled:true,bevelThickness:.025,bevelSize:.025,bevelSegments:3,steps:1});geo.translate(0,0,-d/2);const body=new T.Mesh(geo,mat);body.castShadow=true;body.receiveShadow=true;group.add(body);
const handle=(z,rise)=>tube([[-w*.27,h-.02,z],[-w*.26,h+rise*.65,z],[0,h+rise,z],[w*.26,h+rise*.65,z],[w*.27,h-.02,z]],.026,mat,group);
if([0,1,3,4].includes(i)){handle(d*.37,.36);if(i!==1)handle(-d*.37,.36);}
if([2,5].includes(i)){tube([[-w*.43,h-.03,0],[-w*.47,h+.3,0],[0,h+.52,0],[w*.47,h+.3,0],[w*.43,h-.03,0]],.016,gold,group);box(w*.95,h*.32,.03,0,h*.73,d/2+.035,mat,group);}
box(.13,.075,.04,0,h*.62,d/2+.065,gold,group);
if(i<2){box(w*.82,.045,.025,0,h*.65,d/2+.034,mat,group);for(const x of [-w*.32,w*.32])box(.05,h*.38,.035,x,h*.74,d/2+.048,gold,group);}
if(i===2||i===4){for(let x=-w*.43;x<w*.5;x+=.12)for(let y=.08;y<h-.05;y+=.12){const pts=[[x-.035,y,d/2+.03],[x,y+.04,d/2+.03],[x+.035,y,d/2+.03],[x,y-.04,d/2+.03],[x-.035,y,d/2+.03]];tube(pts,.0025,gold,group);}}
if(i===3){tube([[-w*.42,h*.66,d/2+.03],[0,h*.97,d/2+.03],[w*.42,h*.66,d/2+.03]],.008,gold,group);}
group.userData={bagIndex:i,proxy:true};group.traverse(o=>{if(o.isMesh){o.userData.bagIndex=i;hitObjects.push(o);}});return group;}
bags.forEach((b,i)=>{const [x,z]=placements[i];box(1.6,1.15,1.3,x,.575,z,stone);box(1.65,.05,1.35,x,1.17,z,gold);box(1.48,.035,1.18,x,1.215,z,black);spotlight(x,z);const l=label(b.brand+' · '+b.name,1.45,.24);l.position.set(x,.82,z+.657);scene.add(l);const g=buildProxy(b,i);g.position.set(x,1.24,z);scene.add(g);models.push(g);homes.push(g.position.clone());const btn=document.createElement('button');btn.innerHTML=`<small>${String(i+1).padStart(2,'0')} / ${b.brand.toUpperCase()}</small>${b.name}`;btn.onclick=()=>select(i);$('collection').appendChild(btn);});
let selected=-1,table=-1,mode='gallery',auto=false,entered=false,anim=null,yaw=0,pitch=-.12,distance=2.4,turnX=0,turnY=0;const keys=new Set();
function say(s){$('status').textContent=s;}function select(i){if(anim)return;if(table>=0&&table!==i)putBack(false);selected=i;$('intro').hidden=true;entered=true;const b=bags[i];$('detail').hidden=false;$('number').textContent=`${String(b.index).padStart(3,'0')} / 200 · ${b.brand.toUpperCase()}`;$('name').textContent=b.name;$('sign').textContent=b.sign;$('reference').src=`assets/${b.id}.svg`;$('reference').alt=`${b.brand} ${b.name}, illustration de l’atlante`;$('spec').innerHTML=`<dt>Materia</dt><dd>${b.material}</dd><dt>Ingombro di riferimento · cm</dt><dd>${b.dims.join(' × ')}<br><small>${b.dimensionStatus}</small></dd>`;updateButtons();[...$('collection').children].forEach((c,j)=>c.classList.toggle('active',i===j));say(table===i?'Sul tavolo: trascina per ruotare · rotella per zoomare':'Selezionata: '+b.brand+' '+b.name);}
function updateButtons(){$('take').hidden=table===selected;$('return').hidden=table<0;$('dismiss').hidden=table>=0;for(const id of ['front','back','auto','minus','plus'])$(id).disabled=table<0;}
function moveModel(g,to,done){anim={g,from:g.position.clone(),to,start:performance.now(),done};}
function take(){if(selected<0||anim)return;const i=selected;table=i;mode='inspect';distance=3.0;turnX=turnY=0;auto=false;models[i].rotation.set(0,0,0);moveModel(models[i],new T.Vector3(0,1.15,1.4),()=>say('Sul tavolo: trascina per ruotare · rotella per zoomare'));updateButtons();say('La borsa viene portata sul tavolo…');}
function putBack(animated=true){if(table<0||anim)return;const i=table;table=-1;mode='gallery';auto=false;models[i].rotation.set(0,0,0);if(animated)moveModel(models[i],homes[i],()=>say('La borsa è tornata al suo posto'));else models[i].position.copy(homes[i]);camera.position.set(0,2.25,8.8);yaw=0;pitch=-.12;updateButtons();}
$('take').onclick=take;$('return').onclick=()=>putBack();$('dismiss').onclick=()=>{$('detail').hidden=true;selected=-1;[...$('collection').children].forEach(c=>c.classList.remove('active'));};$('enter').onclick=()=>{$('intro').hidden=true;entered=true;say('Scegli una borsa · trascina per guardarti intorno · WASD per camminare');};$('help').onclick=()=>$('instructions').hidden=false;$('closeHelp').onclick=()=>$('instructions').hidden=true;
$('home').onclick=()=>{if(anim)return;putBack(false);mode='gallery';camera.position.set(0,2.25,10.8);yaw=0;pitch=-.12;say('Vista d’ingresso');};$('walk').onclick=()=>{if(anim)return;putBack(false);mode='gallery';$('intro').hidden=true;entered=true;say('Cammina con WASD o frecce · trascina per guardarti intorno');};$('front').onclick=()=>{turnX=turnY=0;auto=false;};$('back').onclick=()=>{turnX=0;turnY=Math.PI;auto=false;};$('auto').onclick=()=>{auto=!auto;say(auto?'Rotazione automatica attiva':'Rotazione automatica ferma');};$('plus').onclick=()=>distance=Math.max(.9,distance-.2);$('minus').onclick=()=>distance=Math.min(4,distance+.2);
$('sheet').onclick=()=>{if(selected<0)return;keys.clear();const b=bags[selected],url=`schede/${b.id}.html`;$('sheetTitle').textContent=b.brand+' · '+b.name;$('sheetFrame').src=url;$('sheetExternal').href=url;$('sheetDialog').showModal();};$('closeSheet').onclick=()=>$('sheetDialog').close();
const ray=new T.Raycaster(),pointer=new T.Vector2();function intersect(e){pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(hitObjects,false)[0];}
let drag=null,touches=new Map(),pinch=0;const canvas=renderer.domElement;
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);touches.set(e.pointerId,[e.clientX,e.clientY]);drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};});
canvas.addEventListener('pointermove',e=>{if(touches.has(e.pointerId))touches.set(e.pointerId,[e.clientX,e.clientY]);if(touches.size===2){const a=[...touches.values()],d=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);if(pinch&&mode==='inspect')distance=T.MathUtils.clamp(distance+(pinch-d)*.007,.9,4);pinch=d;if(drag)drag.moved=true;return;}if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>5)drag.moved=true;if(mode==='inspect'){turnY+=dx*.009;turnX=T.MathUtils.clamp(turnX+dy*.006,-.65,.65);auto=false;}else{yaw-=dx*.004;pitch=T.MathUtils.clamp(pitch-dy*.003,-.65,.45);}drag.x=e.clientX;drag.y=e.clientY;}else{const h=intersect(e);$('hover').style.display=h?'block':'none';canvas.style.cursor=h?'pointer':'grab';if(h){const b=bags[h.object.userData.bagIndex];$('hover').textContent=b.brand+' · '+b.name;$('hover').style.left=Math.min(e.clientX+16,innerWidth-220)+'px';$('hover').style.top=e.clientY+16+'px';}}});
canvas.addEventListener('pointerup',e=>{touches.delete(e.pointerId);pinch=0;if(drag&&!drag.moved&&mode==='gallery'){const hit=intersect(e);if(hit)select(hit.object.userData.bagIndex);}drag=null;});canvas.addEventListener('pointercancel',()=>{drag=null;touches.clear();pinch=0;});canvas.addEventListener('wheel',e=>{e.preventDefault();if(mode==='inspect')distance=T.MathUtils.clamp(distance+e.deltaY*.002,.9,4);else{const v=new T.Vector3(-Math.sin(yaw),0,-Math.cos(yaw));camera.position.addScaledVector(v,-e.deltaY*.006);constrain();}},{passive:false});
window.addEventListener('keydown',e=>{if($('sheetDialog').open||!$('instructions').hidden)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(e.key==='Escape'&&!anim){if(table>=0)putBack();else $('detail').hidden=true;}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());
function constrain(){camera.position.x=T.MathUtils.clamp(camera.position.x,-7.2,7.2);camera.position.z=T.MathUtils.clamp(camera.position.z,-7.2,11);const obstacles=placements.map(([x,z])=>({x,z,w:1.15,d:1}));obstacles.push({x:0,z:1.4,w:1.7,d:1.25});for(const o of obstacles){const dx=camera.position.x-o.x,dz=camera.position.z-o.z;if(Math.abs(dx)<o.w&&Math.abs(dz)<o.d){if(o.w-Math.abs(dx)<o.d-Math.abs(dz))camera.position.x=o.x+(dx>=0?o.w:-o.w);else camera.position.z=o.z+(dz>=0?o.d:-o.d);}}}
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(anim){const t=Math.min(1,(now-anim.start)/900),s=t*t*(3-2*t);anim.g.position.lerpVectors(anim.from,anim.to,s);anim.g.position.y+=Math.sin(t*Math.PI)*.6;if(t===1){const done=anim.done;anim=null;done();}}
if(mode==='inspect'&&table>=0){if(auto)turnY+=dt*.5;models[table].rotation.set(turnX,turnY,0);const target=new T.Vector3(0,1.62,1.4);const desired=new T.Vector3(.08,1.62+distance*.32,1.4+distance);camera.position.lerp(desired,Math.min(1,dt*5));camera.lookAt(target);}else{if(entered&&!$('sheetDialog').open&&$('instructions').hidden){const forward=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0),side=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);camera.position.x+=(-Math.sin(yaw)*forward+Math.cos(yaw)*side)*dt*2.5;camera.position.z+=(-Math.cos(yaw)*forward-Math.sin(yaw)*side)*dt*2.5;constrain();}camera.lookAt(camera.position.clone().add(new T.Vector3(-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch))));}renderer.render(scene,camera);}
updateButtons();requestAnimationFrame(frame);window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
// A real GLB can replace a proxy through this adapter without changing selection or home positions.
window.Boutique={select,take,putBack,get state(){return {selected,table,mode,animating:!!anim,bagCount:models.length};},replaceModel(i,object){if(anim||table>=0)throw Error('Rimettere prima la borsa sul piedistallo');if(!models[i]||!object?.isObject3D)throw Error('Modello o indice non valido');const old=models[i];scene.remove(old);for(let j=hitObjects.length-1;j>=0;j--)if(hitObjects[j].userData.bagIndex===i)hitObjects.splice(j,1);object.position.copy(homes[i]);object.userData.bagIndex=i;object.traverse(o=>{if(o.isMesh){o.castShadow=true;o.userData.bagIndex=i;hitObjects.push(o);}});scene.add(object);models[i]=object;},capture(){return renderer.domElement.toDataURL('image/png');}};
})();


