(function(root){
'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function geometry(b,dims=b.dims,seam=7){
 let [w,h,d]=dims.map(x=>x*10),p=b.outline.map(([x,y])=>[x*w,y*h]);
 if(b.shape==='cilindro'){w=dims[1]*10;h=dims[2]*10;d=dims[0]*10;p=b.outline.map(([x,y])=>[x*w,y*h])}
 let lengths=p.map((a,i)=>Math.hypot(p[(i+1)%p.length][0]-a[0],p[(i+1)%p.length][1]-a[1])),perimeter=lengths.reduce((a,c)=>a+c,0);
 let area=p.reduce((s,a,i)=>s+a[0]*p[(i+1)%p.length][1]-p[(i+1)%p.length][0]*a[1],0)/2;
 const offset=p.map((v,i)=>{let a=p[(i+p.length-1)%p.length],c=p[(i+1)%p.length],e=[v[0]-a[0],v[1]-a[1]],f=[c[0]-v[0],c[1]-v[1]],le=Math.hypot(...e),lf=Math.hypot(...f),sg=area>0?1:-1,n1=[sg*e[1]/le,-sg*e[0]/le],n2=[sg*f[1]/lf,-sg*f[0]/lf],den=1+n1[0]*n2[0]+n1[1]*n2[1],q=Math.min(seam/Math.max(.15,den),seam*3);return [v[0]+q*(n1[0]+n2[0]),v[1]+q*(n1[1]+n2[1])]});
 return {w,h,d,p,offset,perimeter,lengths,seam,area:Math.abs(area),zip:Math.min(w*.72,perimeter*.24)};
}
function pattern(b,dims=b.dims,seam=7){
 const g=geometry(b,dims,seam),{w,h,d,p,offset,perimeter:P}=g;const pad=40,margin=seam+14,W=Math.max(2*w+3*pad+4*seam,P+2*pad+2*seam,1280),H=215+h+d+180;let parts=[];
 function poly(points,x,y,attrs){return `<polygon points="${points.map(([a,c])=>(a+x).toFixed(2)+','+(c+y).toFixed(2)).join(' ')}" ${attrs}/>`}
 function txt(x,y,t,size=7){return `<text x="${x}" y="${y}" font-size="${size}" fill="#263a3c">${esc(t)}</text>`}
 for(let j=0;j<2;j++){let x=pad+seam+j*(w+pad+2*seam),y=100+seam;parts.push(poly(offset,x,y,'fill="#f6efe2" stroke="#253a3c" stroke-width=".55"'),poly(p,x,y,'fill="none" stroke="#b4603e" stroke-width=".5" stroke-dasharray="3 2"'),txt(x,y+h+18,(j?'B · RETRO':'A · FRONTE')+' — tagliare 1 + eventuale fodera',6));parts.push(`<path d="M${x+w*.5},${y+h*.3}v${h*.38}" stroke="#4b7976" stroke-width=".6" marker-end="url(#arrow)"/>`,txt(x+w*.5+5,y+h*.5,'direzione materiale',4));let accum=0;for(let i=0;i<p.length;i++){if(i%Math.max(1,Math.floor(p.length/8))===0){parts.push(`<circle cx="${x+p[i][0]}" cy="${y+p[i][1]}" r="1.2" fill="#b4603e"/>`,txt(x+p[i][0]+2,y+p[i][1]-2,'R'+i,3.6))}accum+=g.lengths[i]}}
 let yy=100+seam+h+50;parts.push(`<rect x="${pad}" y="${yy}" width="${P+2*seam}" height="${d+2*seam}" fill="#edf3ee" stroke="#253a3c" stroke-width=".55"/><rect x="${pad+seam}" y="${yy+seam}" width="${P}" height="${d}" fill="none" stroke="#b4603e" stroke-width=".5" stroke-dasharray="3 2"/>`);let cum=0;g.p.forEach((v,i)=>{if(i%Math.max(1,Math.floor(p.length/8))===0)parts.push(`<path d="M${pad+seam+cum},${yy+seam}v${d}" stroke="#668c87" stroke-width=".3" stroke-dasharray="2 2"/>`,txt(pad+seam+cum+2,yy+seam+5,'R'+i,3.5));cum+=g.lengths[i]});parts.push(`<path d="M${pad+seam+P*.03},${yy+seam+d/2}h${g.zip}" stroke="#5f5b93" stroke-width="1.5"/>`,txt(pad,yy+d+2*seam+13,`C · FASCIA CONTINUA — linea cucitura ${P.toFixed(1)} × ${d.toFixed(1)} mm; unire estremità corte. Tratto viola: apertura zip di studio.`,6));
 let sy=yy+d+2*seam+32;parts.push(`<rect x="${pad}" y="${sy}" width="1200" height="${25+2*seam}" fill="#f7f2e7" stroke="#253a3c" stroke-width=".55"/><path d="M${pad},${sy+seam+12.5}h1200" stroke="#668c87" stroke-width=".4" stroke-dasharray="3 3"/>`,txt(pad,sy+25+2*seam+12,'D · TRACOLLA OPZIONALE — lunghezza 1200 mm, larghezza finita 25 mm; adattare attacchi e rinforzi al prototipo.',6));
 return `<svg xmlns="http://www.w3.org/2000/svg" width="${W.toFixed(2)}mm" height="${H.toFixed(2)}mm" viewBox="0 0 ${W} ${H}"><defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="3" refY="3" orient="auto"><path d="M0,0L6,3 0,6Z" fill="#4b7976"/></marker></defs><rect width="100%" height="100%" fill="white"/><g font-family="Arial,sans-serif">${txt(pad,20,`FORME / ${b.brand} · ${b.name}`,11)}${txt(pad,33,'RICOSTRUZIONE GEOMETRICA DIDATTICA — non cartamodello originale né replica di produzione.',7)}${txt(pad,45,`Ingombro L × H × P: ${dims.join(' × ')} cm · dati: ${b.dimensionStatus} · margine nominale ${seam} mm.`,6)}${txt(pad,56,'Contorno scuro: taglio approssimato; arancio: cucitura; verde: riferimenti. Provare prima in tela. Verificare margini nelle concavità.',5.5)}${txt(pad,67,'La fascia misura il perimetro campionato dei pannelli. Rinforzi, fodera, spessori e chiusure di marca non sono ricostruiti.',5.5)}<rect x="${W-75}" y="20" width="50" height="50" fill="none" stroke="#263a3c" stroke-width=".5"/>${txt(W-74,78,'CONTROLLO 50 × 50 mm',4)}${parts.join('')}</g></svg>`;
}
function dxf(b,dims=b.dims,seam=7){let g=geometry(b,dims,seam),s='0\nSECTION\n2\nHEADER\n9\n$INSUNITS\n70\n4\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n';function poly(p,dx,dy,layer){s+='0\nLWPOLYLINE\n100\nAcDbEntity\n8\n'+layer+'\n100\nAcDbPolyline\n90\n'+p.length+'\n70\n1\n';p.forEach(([x,y])=>s+='10\n'+(x+dx).toFixed(4)+'\n20\n'+(-y-dy).toFixed(4)+'\n')};[0,g.w+60].forEach(x=>{poly(g.p,x,0,'CUCITURA');poly(g.offset,x,0,'TAGLIO_STUDIO')});poly([[0,0],[g.perimeter,0],[g.perimeter,g.d],[0,g.d]],0,g.h+60,'CUCITURA');poly([[-seam,-seam],[g.perimeter+seam,-seam],[g.perimeter+seam,g.d+seam],[-seam,g.d+seam]],0,g.h+60,'TAGLIO_STUDIO');return s+'0\nENDSEC\n0\nEOF\n'}
root.BagGeometry={geometry,pattern,dxf};if(typeof module!=='undefined')module.exports=root.BagGeometry;
})(typeof window==='undefined'?globalThis:window);
